### ISSUE TITLE
Connector should (re-)broadcast scale and precision along with routes.

### ISSUE THREAD

**Issue by justmoon** [interledgerjs/ilp-connector#270]
Prerequisite for #269. Please see that ticket for more context / motivation.

This should be implemented in a backwards-compatible way, meaning if a connector does not receive scale and precision information from another connector it should behave as it does now. It MUST always broadcast scale and precision for any ledger that it is the final destination for. For any other destination, it will forward the scale and precision information (or lack thereof) that it received.

**Comment by sentientwaffle** [comment]
Fixed by https://github.com/interledgerjs/ilp-connector/pull/275
