### ISSUE TITLE
Create a Yahoo Exchange Rate API backend

### ISSUE THREAD

**Issue by justmoon** [interledgerjs/ilp-connector#279]
Suggestion by @Winthan:

> btw, can we use Yahoo's Exchange API than fixer.io. The Yahoo Exchange can cover most of the currencies as well as BTC/Gold/Slivers so on.
>
> `https://query.yahooapis.com/v1/public/yql?q=select * from yahoo.finance.xchange where pair in ("USDAUD", "USDAED", "USDARS", "USDAOA", "USDBGN", "USDBRL", "USDBTC", "USDBRL", "USDCAD", "USDCHF", "USDCNY", "USDCZK", "USDDKK", "USDEUR", "USDGBP", "USDHKD", "USDHRK", "USDHUF", "USDIDR", "USDILS", "USDISK", "USDLTL", "USDLVL", "USDRON", "USDJPY", "USDKRW", "USDMMK", "USDMXN", "USDMYR", "USDMZN", "USDNOK", "USDNZD", "USDPHP", "USDPLN", "USDRON", "USDRUB", "USDSEK", "USDSGD", "USDTHB", "USDTRY", "USDTWD", "USDXAG", "USDXAU", "USDZAR")&env=store://datatables.org/alltableswithkeys&format=json`

**Comment by sharafian** [comment]
https://github.com/interledgerjs/ilp-connector-backend-yahoo @emschwartz created a repository for this

**Comment by Winthan** [comment]
Yes, @emschwartz created Yahoo connector and it works great.
