### ISSUE TITLE
Connector is blocked if initial websocket connection to one of its ledgers never connects

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-connector#309]
If one of the ledgers never connects via websockets, the connector will never start broadcasting routes because [this promise](https://github.com/interledgerjs/ilp-connector/blob/master/src/app.js#L32) never resolves.

**Comment by sentientwaffle** [comment]
What's the correct behavior? Should it keep trying to connect in the background indefinitely while allowing the connector to operate normally (minus one ledger plugin)?

**Comment by emschwartz** [comment]
I think so. I would mark that ledger as unreachable and keep going with what is working.

https://github.com/interledgerjs/ilp-plugin-bells/pull/99 also made it harder to figure out why this wasn't working
