### ISSUE TITLE
If the connector is the receiver of a transfer he rejects the transfer

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-connector#335]
When sending a payment to the connector account, it sometimes rejects the transfer. This happens for example when a new ILP Kit is setup and the connector account receives the initial funding (see interledgerjs/ilp-kit#316 and interledgerjs/ilp-kit#335).

This is the log message (`us.usd.wallet1.connie` is the connector):

```
connector:payments debug rejecting incoming transfer id=01d2237e-68ba-4b5d-8023-59f1271fb63d reason={
  "triggered_by": "us.usd.wallet1.connie",
  "triggered_at": "2017-05-02T14:11:31.648Z",
  "additional_info": {},
  "code": "S02",
  "name": "Unreachable",
  "message": "No route found from: us.usd.wallet1. to: us.usd.wallet1.connie.8QLr-0lKvYgx32i-Th3yXMQsHxjcSOJLg"
}
```

It seems to be a race between `ilp-plugin-bells`, which tries to fulfill the transfer, and the routing logic, which fails trying to route the transfer to itself and, in consequense, rejects the payment.

Should the routing logic check if the receiver of the transfer is the connector itself and do nothing in that case?

**Comment by michielbdejong** [comment]
yes, probably add a check for that, here: https://github.com/interledgerjs/ilp-connector/blob/4ff8f345aaea5dec11d02803743b8f39a7a97302/src/models/subscriptions.js#L8

Just wondering - why was this not a problem earlier, do we know what changed?

**Comment by dappelt** [comment]
Fixed in [this](https://github.com/interledgerjs/ilp-connector/commit/6ca789fc3037199bb2993388dabdff2d28f33183) commit.
