### ISSUE TITLE
What if route broadcasts were binding?

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-connector#347]
From #344:
> not including cost in automatic routing at all

I thought about that some more, and my thoughts ended up going in the opposite direction: what if we keep the cost information both in route broadcasts and in quote responses, but we could somehow make it binding, so that blame can be assigned automatically?

When Derek bluffs about a route, Charlie may base his routes on that, forwarding that information to Bob, meaning Alice's payment ends up failing. Alice would blame Bob, Bob would blame Charlie, and Charlie would blame Derek, meaning not only Derek, but also Bob and Charlie lose credibility, and Alice loses time, having to retry her payment.

But for Derek to announce a route to Charlie, it is necessary for them to be peered, probably through a trustline, whose balance represents some "realness" for both Charlie and Derek. If the route broadcast would include a guaranteed volume, Derek could announce this route "or your money back". And once Derek does that, Charlie is in a position to make a similar guarantee.

A special kind of payment failure is when a payment is routed correctly to the destination ledger, but the receiver can not or does not fulfill it, that's not the fault of any of the connectors; in that case, you would need a signed error response from the destination ledger saying 'delivered to the destination ledger on time, for the correct destination amount, but receiver did not fulfill', and it would not be necessary to blame any of the connectors. So a route broadcast would then include something like:

* ledger prefix
* ledger pubkey (for signed error responses)
* curve
* forwarding fee
* failure penalty
* volume guarantee (the value that is currently already expressed by the curve that ends in a horizontal line, but now also as a maximum accumulative value for a series of payments, not just the max for one payment)

The rules of the trustline would then be the same in case of success, but different in case of failure:

* If a signed error response from the destination ledger is presented, the sending connector has to pay the forwarding fee.
* If not, the receiving connector has to pay the failure penalty.

These can be forwarded, so that if Alice makes a payment to Edward, but Edward doesn't fulfil it, Alice has to pay the forwarding fees. But if the payment fails due to an intermediate connector not keeping their promise, then Alice can be reimbursed a failure penalty.

Connectors will avoid paying failure penalties, and therefore stop bluffing, both in route broadcasts and in quote responses.

**Comment by michielbdejong** [comment]
Another solution would be to make the Interledger a best-effort network where forwarding traffic is doing your peers a favor, not something you get rich from.

**Comment by adrianhopebailie** [comment]
> Another solution would be to make the Interledger a best-effort network where forwarding traffic is doing your peers a favor, not something you get rich from.

I think this is the direction things will go in. The ability to charge a premium for routing will depend on the trust people can place in your route broadcasts.

**Comment by michielbdejong** [comment]
Closing this for now; first, let's fix what we have.
