### ISSUE TITLE
Expose async listen function

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-connector#356]
The connector.listen function is now a function that returns (almost) immediately, and then does the actual work in the background. My hypothesis is that this is what's causing the current intermittent integration test failures.

**Comment by michielbdejong** [comment]
One obstacle to making it an async function is that it's past through `_.partial` before being exposed to by the module. We could also add an additional `async function ready()` so that the we don't break the current API?

**Comment by emschwartz** [comment]
Arguably the connector should "start" and say it's ready as soon as it can. Earlier it waited for all of the ledgers to connect and that caused problems of its own

**Comment by sentientwaffle** [comment]
Closed by https://github.com/interledgerjs/ilp-connector/pull/384
