### ISSUE TITLE
non-increasing curves found in alpha network

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-connector#361]
Seeing:
```sh
[api] 2017-07-04T08:38:06.501Z connector:message-router warn error broadcasting routes: Curve x-coordinates must strictly increase in series points:[[2,0],[3,0],[3,0],[4,1],[999999989,994011978],[1000000001,994011990],[100000000000001,994011990]]
```

 in the logs of one of the nodes in the alpha network. When creating, joining, or combining a curve, there should be a simplification step where the first two points of that curve (maybe even the first three?) are discarded. We should also handle infinity differently so that there are not 3 points that all try to indicate the exchange rate for some high PROBE_SOURCE_AMOUNT number.

**Comment by michielbdejong** [comment]
i think we can make 2 improvements:
* remove points at the left until y > 0 for the first point
* remove points at the right until y < 1000 USD for the point before last (so only the very last point is allowed to exceed 1000 USD)

**Comment by sharafian** [comment]
did we ever conclude our discussion of whether the curve is actually needed? It's causing us so many problems in our network, and all we're using it for is expressing a rate that could just as easily be a single number.

**Comment by michielbdejong** [comment]
we've only just started to use if for liquidity routing, which I think is important for the current use case of paying lunch. we've been talking about micropayments to content providers, but i think we're several months away from actually seeing such use in practice.

if and when a new use case is decided on, it's possible that curves become less important, but for now, we should at least fix them, i think

**Comment by sharafian** [comment]
Even for our lunch use case, that's just a maximum and a rate, no need for these complicated curves.

**Comment by michielbdejong** [comment]
when interpreting a curve, I think its meaning should be:
* if you send less than the first point's source amount, expect a destination amount of zero
* if you send more than the last point's source amount, expect a destination amount equal to that of the last point - in other words, the curve becomes horizontal after the last point

other interpretation guidelines (not related to this change):
* in between curve points, you should round in the publisher's favor to get exact exchange rates
* you might be able to round in your own favor, especially if markets moved since the curve was created
* even if you round in the publisher's favor, there is never a promise or guarantee. it's just an indication that the publisher can *probably* deliver the rates announced, at least once.
* there is no indication of how often you can repeat payments at the announced rate before the market dries up, just try it out, and when it starts failing, get a new quote.

**Comment by michielbdejong** [comment]
> just a maximum and a rate

not if we start doing auto-reflow (or whatever we call it) and also not if different nodes have different rates. then there might be a cheap route with a low maximum, and a more expensive one with a higher maximum

**Comment by sharafian** [comment]
just a strawman proposal, but what if instead of a list of coordinates (which have proven to be hard to deal with), we had a list of rates (slopes) and maximums. So instead of looking like a single complex line, it would be several very simple lines coming out of the origin.

No simplification step would be strictly necessary, although if you sort by best price you can discard anything that's has a lower maximum than the previous element.

In order to find the best quote for an amount, just sort by best price and filter anything with maximum lower than your amount. Then return the first element.

These algorithms seem easier than what we have now, and with fewer edge cases (although I've not fully investigated them). There is also a case to be made to fix what we have instead of writing something new.

**Comment by michielbdejong** [comment]
found the curves that it fails to combine, here's the failing unit test:

```js
    it('cleans up duplicate points', function () {
      const curve1 = new LiquidityCurve([ [1, 0], [50000000001, 49800199999], [100000000000001, 49800199999] ])
      const curve2 = new LiquidityCurve([ [2, 0], [50000000001, 49800199999], [100000000000001, 49800199999] ])
      const combinedCurve = curve1.combine(curve2)

      assert.deepStrictEqual(combinedCurve.getPoints(),
        [ [1, 0], [2, 0], [50000000001, 49800199999], [100000000000001, 49800199999] ])
    })
```

```sh
  99 passing (111ms)
  1 failing

  1) LiquidityCurve combine cleans up duplicate points:
     InvalidLiquidityCurveError: Curve x-coordinates must strictly increase in series points:[[1,0],[2,0],[50000000001,49800199999],[50000000001,49800199999],[100000000000001,49800199999]]
      at LiquidityCurve.setData (src/lib/liquidity-curve.js:31:15)
      at new LiquidityCurve (src/lib/liquidity-curve.js:15:12)
      at LiquidityCurve.combine (src/lib/liquidity-curve.js:118:12)
      at Context.<anonymous> (test/liquidity-curve.test.js:138:36)
```

Will fix in the ilp-routing repo
