### ISSUE TITLE
Rate error when currency scales don't match when using configured routes?

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-connector#378]
When using configured routes, and quoting between two ledgers, one that's nano-USD and one that's centi-USD, the ratio between source and destination amount is off by a factor 10^7. This is probably due to [the `CONNECTOR_LEDGERS` format](https://github.com/interledgerjs/ilp-connector/blob/master/test/ilpQuoterSpec.js#L30-L37) which still uses the old 'currency' field, from the days when amounts were expressed as floats.

**Comment by michielbdejong** [comment]
cc @sharafian @sentientwaffle

**Comment by sentientwaffle** [comment]
What backend is your connector using? And is this post-connector 21.0.7?

**Comment by michielbdejong** [comment]
I think this is probably latest master, with the fixerio backend (but it was @sharafian who discovered this bug, I only reported it on his behalf)

**Comment by sentientwaffle** [comment]
Ok, I talked to @sharafian and it sounds like it was `ilp-connector@21.0.1`. This issue was fixed in `ilp-connector@21.0.7`.
