### ISSUE TITLE
Accounts realtime update

### ISSUE THREAD

**Issue by elmurci** [interledgerjs/ilp-connector#477]
Right now accounts configuration is passed to the connector on start up.
For large systems and with constant real time additions/changes to accounts this is not scalable.

Shouldn't the Connector have the Plugin offer a getAccount method to check in realtime whether the account exists/has balance/is blocked...?

**Comment by sentientwaffle** [comment]
https://github.com/interledgerjs/ilp-connector/pull/476 is a step in that direction (albeit with a different approach than you describe).

**Comment by elmurci** [comment]
Thanks @sentientwaffle, it seems to me that having the connector to keep track of accounts is not scalable.

**Comment by kincaidoneil** [comment]
For reference, [our connector configuration](https://github.com/Kava-Labs/connector-config/blob/master/run-connector.js) adds, removes and hot-swaps accounts without restarting, using the current ilp-connector.

The admin API HTTP endpoints (or calling `getPlugin` and then invoking `getAdminInfo`) enables querying the balance and whether the peer is blocked for `xrp-asym-server` (I'm not sure about the other XRP plugins, but that's not currently supported by Lightning or Eth).

As DJ mentioned, #476 should make this easier and standardized as plugins are updated to support it.

**Comment by elmurci** [comment]
Thanks @kincaidoneil, have you guys tested performance with thousands or hundreds of thousands of accounts?

**Comment by sentientwaffle** [comment]
I think you may be misunderstanding what an "account" is in the connector. Usually a connector will have only need one account per plugin type. Plugins based on [ilp-plugin-mini-accounts](https://github.com/interledgerjs/ilp-plugin-mini-accounts) allow many users to access a connector without the connector ever reconfiguring.

**Comment by elmurci** [comment]
@sentientwaffle So if I am a ILSP, wouldn't I have as many accounts as users?

**Comment by sentientwaffle** [comment]
Correct

**Comment by elmurci** [comment]
So I think what you mean is as a Connector I will have 1 account per plugin type/ledger, but as a many accounts for my users as I need outside the connector. 

Correct?

**Comment by sentientwaffle** [comment]
Yes

**Comment by elmurci** [comment]
👍Thanks
