### ISSUE TITLE
Argument of type 'MemDown<any, any>' is not assignable

### ISSUE THREAD

**Issue by martinlowinski** [interledgerjs/ilp-connector#483]
Hi,

when building the project via `npm run build`, I get the following TypeScript error:

```
> ilp-connector@22.3.1 build /home/cobolt/Projects/moneytransfair/ilp-connector
> npm run schema-to-tsd && npm run compile-ts


> ilp-connector@22.3.1 schema-to-tsd /home/cobolt/Projects/moneytransfair/ilp-connector
> node scripts/build_schema_types


> ilp-connector@22.3.1 compile-ts /home/cobolt/Projects/moneytransfair/ilp-connector
> tsc --project .

src/stores/memdown.ts:11:24 - error TS2345: Argument of type 'MemDown<any, any>' is not assignable to parameter of type 'AbstractLevelDOWN<any, any, any, any, any, any, any, any>'.
  Types of property 'iterator' are incompatible.
    Type '(options?: (MemDownIteratorOptions & AbstractIteratorOptions<any>) | undefined) => AbstractIterator<any, any>' is not assignable to type '(options?: any) => AbstractIterator<any, any>'.
      Property 'db' is missing in type 'AbstractIterator<any, any>' but required in type 'AbstractIterator<any, any>'.

11     const db = levelup(memdown(path || 'connector-main'))
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/abstract-leveldown/index.d.ts:57:3
    57   db: any;
         ~~
    'db' is declared here.


Found 1 error.
```

I am using node v8.10.0 and npm v3.5.2.

**Comment by sentientwaffle** [comment]
Were there any errors when you ran `npm install`?

What versions of leveldown/levelup/memdown are installed?

Also, it might be worth trying a newer node version (e.g. v10.x.x) to see if that solves the problem.

**Comment by martinlowinski** [comment]
There were no errors for `npm install`, just warnings:
- table@4.0.2 UNMET PEER DEPENDENCY ajv@5.5.2
- npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
- npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7
- npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none was installed.

Versions of leveldown/levelup/memdown/.. are:
- @types/abstract-leveldown: 5.0.1
- abstract-leveldown: 4.0.0
- deferred-leveldown: 2.0.3
- @types/levelup: 3.1.0
- memdown: 1.4.1

**Comment by sentientwaffle** [comment]
Those version all match up to what I have locally. I just installed node v8.10.0 and the connector worked just fine, so I'm not sure what the problem is.

You didn't mention what version of `levelup` and `leveldown` you have installed, though (`npm ls leveldown` and `npm ls levelup`).

**Comment by martinlowinski** [comment]
Sorry, missed that.
- leveldown@3.0.0
- levelup@2.0.1

I just installed node v10.15.3, `npm install` shows lots of warnings when building leveldown, `npm run build` works though. Maybe it was an npm issue, I have now v6.4.1, before it was v3.5.2.

Thanks for the support!

**Comment by sentientwaffle** [comment]
The levelup/leveldown version match mine as well.

I'm glad to hear it's working on the new node/npm version.
