### ISSUE TITLE
Support Node 12

### ISSUE THREAD

**Issue by dacioromero** [interledgerjs/ilp-connector#494]
Installing package in Node 12.13.0 crashes. I admittedly know little about how leveldown and levelup are used, but it would be great to have this package work in Node 12 now that it is LTS.

> Conversely, for node >= 12, the minimum leveldown version is 5.0.0.
\- [leveldown README](https://github.com/Level/leveldown/blob/975ea2a594765f9d4d2d45b1f77c2dddb83c7936/README.md#supported-platforms)

https://github.com/Level/leveldown/blob/master/UPGRADING.md
https://github.com/Level/levelup/blob/master/UPGRADING.md

**Comment by intelliot** [comment]
Fixed in ilp-connector v23.0.0 https://github.com/interledgerjs/ilp-connector/commit/9314e9968818fd16b1e482a544018f0225f7f5ce
