### ISSUE TITLE
Example run error

### ISSUE THREAD

**Issue by Srtake** [interledgerjs/ilp-connector#500]
# Description
I tried to run the example code in `examples/example-using-LPI-V2.js`, but got an error:
`
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'expiresAt' of undefined
    at Object.serializeIldcpRequest ($PROJECT_DIR\node_modules\ilp-protocol-ildcp\src\index.ts:47:24)
`

# Analysis
In line 25 of `example-using-LPI-V2.js`, `sendData()` accepts the return value of `Ildcp.serializeIldcpRequest()` as its parameter, which needs to input a `IldcpRequest` object. However, there is not any object input.

# Excepted Behaviour
Code run successfully and log `It worked!` in console, as line 35 says.

**Comment by sentientwaffle** [comment]
@Srtake Thank you for reporting this! It looks like `serializeIldcpRequest`'s API changed at some point but the example wasn't updated.
