### ISSUE TITLE
Retry ledger requests

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-connector#71]
If connectors receive 500 or other errors from the ledgers while putting transfers they should retry sending them. This is extremely important on the execution side in Universal mode, because if they don't retry they will lose money when transfers time out

**Comment by michielbdejong** [comment]
I think this was fixed, right?

**Comment by dappelt** [comment]
Yes, this was fixed here: https://github.com/interledgerjs/ilp-connector/commit/4ff8f345aaea5dec11d02803743b8f39a7a97302
